apiVersion: v1
kind: Service
metadata:
  name: nats-svc
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
    - name: client
      port: 4222
    - name: leafnodes
      port: 7422
    - name: monitor
      port: 8222
---
apiVersion: v1
kind: Service
metadata:
  name: nats-hlsvc
  labels:
    app: nats
spec:
  selector:
    app: nats
  clusterIP: None
  ports:
    - name: cluster
      port: 6222